import { API_BASE_URL } from '../config/api';
import { getApiHeaders } from './api';

/**
 * Farming Plan Service
 * Integrates with Phase 1 backend APIs
 * DO NOT MODIFY BACKEND - Use APIs exactly as documented
 */

export interface Activity {
  _id?: string;
  activityType: string;
  description: string;
  descriptionTamil?: string;
  scheduledDate: string;
  completionDate?: string;
  status: 'pending' | 'in_progress' | 'completed' | 'skipped';
  actualCost?: number;
  estimatedCost?: number;
  isOptional?: boolean;
  autoGenerated?: boolean;
  generatedReason?: string;
  generatedReasonTamil?: string;
  durationDays?: number;
}

export interface FarmingPlan {
  _id: string;
  userId: string;
  landId: string;
  cropName: string;
  planName: string;
  status: 'draft' | 'active' | 'completed' | 'cancelled';
  startDate: string;
  totalBudget: number;
  plannedAreaHectares: number;
  activities: Activity[];
  progress: {
    percentage: number;
    currentStage: string;
  };
  actualCosts: {
    totalSpent: number;
  };
  aiSuggestions: any[];
  createdAt: string;
}

export interface GeneratedActivity {
  activityType: string;
  description: string;
  descriptionTamil: string;
  scheduledDate: string;
  status: 'pending';
  estimatedCost: number;
  isOptional: boolean;
  durationDays: number;
  autoGenerated: boolean;
  generatedReason: string;
  generatedReasonTamil: string;
}

export interface AISuggestion {
  title: string;
  descriptionEnglish: string;
  descriptionTamil: string;
  type: 'materials' | 'timing' | 'cost' | 'weather' | 'general';
  priority: 'high' | 'medium' | 'low';
}

export interface WeatherForecast {
  date: Date;
  temp: { min: number; max: number; avg: number };
  humidity: number;
  rainfallAmount: number;
  rainfallProbability: number;
  windSpeed: number;
  uvIndex: number;
  irrigationNeeded: boolean;
  pestRisk: 'low' | 'medium' | 'high';
  diseaseRisk: 'low' | 'medium' | 'high';
  heatStress: boolean;
  coldStress: boolean;
  favorableConditions: boolean;
}

export interface WeatherDecision {
  shouldDelay: boolean;
  action: 'delay' | 'proceed' | 'skip' | 'warning';
  reason: string;
  reasonTamil: string;
  suggestedDate?: string;
  weatherData: WeatherForecast;
}

export interface Notification {
  _id: string;
  userId: string;
  planId: string;
  activityId: string;
  type: 'reminder' | 'due' | 'overdue' | 'weather' | 'summary';
  titleEnglish: string;
  titleTamil: string;
  messageEnglish: string;
  messageTamil: string;
  scheduledFor: string;
  deliveredAt?: string;
  readAt?: string;
  status: 'pending' | 'delivered' | 'read' | 'responded' | 'failed';
  priority: 'high' | 'medium' | 'low';
  response?: {
    action: 'completed' | 'reschedule' | 'skip' | 'dismiss';
    respondedAt?: string;
    rescheduleDetails?: {
      oldDate: string;
      newDate: string;
      reason: 'rain' | 'labour' | 'budget' | 'health' | 'weather' | 'other';
      farmerNote?: string;
    };
  };
}

/**
 * Auto-generate activities from crop calendar
 */
export const generateActivities = async (planId: string, season: string = 'all'): Promise<{
  success: boolean;
  activities: GeneratedActivity[];
  count: number;
  message: string;
}> => {
  const response = await fetch(`${API_BASE_URL}/farming-plans/${planId}/generate-activities`, {
    method: 'POST',
    headers: getApiHeaders(),
    body: JSON.stringify({ season })
  });

  if (!response.ok) {
    throw new Error('Failed to generate activities');
  }

  return response.json();
};

/**
 * Accept auto-generated activities
 */
export const acceptGeneratedActivities = async (planId: string, activities: GeneratedActivity[]): Promise<{
  success: boolean;
  plan: FarmingPlan;
  message: string;
}> => {
  const response = await fetch(`${API_BASE_URL}/farming-plans/${planId}/accept-generated-activities`, {
    method: 'POST',
    headers: getApiHeaders(),
    body: JSON.stringify({ activities })
  });

  if (!response.ok) {
    throw new Error('Failed to accept activities');
  }

  return response.json();
};

/**
 * Get AI activity suggestions
 */
export const getActivitySuggestions = async (planId: string, activityType: string): Promise<{
  success: boolean;
  activityType: string;
  suggestions: AISuggestion[];
}> => {
  const response = await fetch(
    `${API_BASE_URL}/farming-plans/${planId}/activity-suggestions/${activityType}`,
    { headers: getApiHeaders() }
  );

  if (!response.ok) {
    throw new Error('Failed to get suggestions');
  }

  return response.json();
};

/**
 * Get weather forecast for plan
 */
export const getWeatherForecast = async (planId: string): Promise<{
  success: boolean;
  forecast: {
    planId: string;
    location: any;
    forecast: WeatherForecast[];
    snapshotDate: string;
  };
}> => {
  const response = await fetch(`${API_BASE_URL}/farming-plans/${planId}/weather-forecast`, {
    headers: getApiHeaders()
  });

  if (!response.ok) {
    throw new Error('Failed to get weather forecast');
  }

  return response.json();
};

/**
 * Check if activity should be delayed due to weather
 */
export const checkWeatherDelay = async (planId: string, activityId: string): Promise<WeatherDecision> => {
  const response = await fetch(`${API_BASE_URL}/farming-plans/${planId}/weather-check/${activityId}`, {
    method: 'POST',
    headers: getApiHeaders()
  });

  if (!response.ok) {
    throw new Error('Failed to check weather delay');
  }

  return response.json();
};

/**
 * Get notifications for user
 */
export const getUserNotifications = async (userId: string, limit: number = 20): Promise<{
  success: boolean;
  notifications: Notification[];
  count: number;
}> => {
  const response = await fetch(
    `${API_BASE_URL}/farming-plans/notifications/user/${userId}?limit=${limit}`,
    { headers: getApiHeaders() }
  );

  if (!response.ok) {
    throw new Error('Failed to get notifications');
  }

  return response.json();
};

/**
 * Respond to notification
 */
export const respondToNotification = async (
  notificationId: string,
  action: 'completed' | 'reschedule' | 'skip' | 'dismiss',
  responseData?: {
    newDate?: string;
    reason?: 'rain' | 'labour' | 'budget' | 'health' | 'weather' | 'other';
    note?: string;
  }
): Promise<{
  success: boolean;
  notification: Notification;
  message: string;
}> => {
  const response = await fetch(
    `${API_BASE_URL}/farming-plans/notifications/${notificationId}/respond`,
    {
      method: 'POST',
      headers: getApiHeaders(),
      body: JSON.stringify({ action, ...responseData })
    }
  );

  if (!response.ok) {
    throw new Error('Failed to respond to notification');
  }

  return response.json();
};

/**
 * Mark notification as read
 */
export const markNotificationAsRead = async (notificationId: string): Promise<{
  success: boolean;
  message: string;
}> => {
  const response = await fetch(
    `${API_BASE_URL}/farming-plans/notifications/${notificationId}/read`,
    {
      method: 'PUT',
      headers: getApiHeaders()
    }
  );

  if (!response.ok) {
    throw new Error('Failed to mark notification as read');
  }

  return response.json();
};

/**
 * Get notification statistics
 */
export const getNotificationStats = async (userId: string): Promise<{
  success: boolean;
  stats: {
    pending: number;
    delivered: number;
    read: number;
    responded: number;
    failed: number;
  };
}> => {
  const response = await fetch(
    `${API_BASE_URL}/farming-plans/notifications/stats/${userId}`,
    { headers: getApiHeaders() }
  );

  if (!response.ok) {
    throw new Error('Failed to get notification stats');
  }

  return response.json();
};
